sudo: required
language: node_js
node_js:
  - "0.10"
before_install:
 - sudo apt-get update -qq
after_success:
 - ./node_modules/.bin/istanbul cover -x "**/spec/**" ./node_modules/.bin/_mocha --report lcovonly -- $(find spec -name '*-spec.js') -R spec --require spec/helper.js
 - cat ./coverage/lcov.info | node_modules/.bin/coveralls

notifications:
  slack:
    rooms:
    - secure: "BXEmODG5+N5MBYsNygzLE3HOZ6FC/MSgoMB7/1BVakQ8z/jjQMiN/loyOa7x/BcOOLIHG3b8ywlqi3a8zaUn1LUhQBagwU5YXt7ViCQX6TIPU54zkdgaJJMQYj7sXuuGa+Dju4ZxCsf1N1zuJXjJvRsHy1fa+O5jAmiRweBxTmi8I9EtUJocUYQDIbZtbFQQJC2m8WDAT9bloNDM5XolEeCTwV222Bb7aayBbGJxWbRGvPgwkOIhEV9hr90CW2OuBb16FEt+Uhmgpx+rfJPA7vVUCqD76NJUEB4rRYeu2E8w9StUIpu6Vz9zIQKCYWivV2UZsc/APZxgIPz9q+9H4AcorEXNBLSLIyl+XKyEb5SO1O3KTC3OxCQjpdzyT5QhcM5SRIcGMXRuSZZlCCxRsQwbVSE0axhzF9EPlGJQkUWSLG5zG2dEJKp/JHgvvPjSJqatDcYeWNt2xeOAumuuTR4XqdACwrNm0Ljf4J625/RE8GMh44ZBrLduL+lgpNAlB2KT/8j3xlNOJoOq/SmTvAo46KG8vH16LnjmJr/G1Ba8ATQxQWD2aNmPOt71N1m1KPC8sYSF3UTZtmVu/snuzrFpDkQCw4f3O545fxaB8y1IRNgFdGOTEL+iS4Wtzcugn4GKr16o9Xbwkq6yEo6VR6BY/zJNv/WIdouoTwbCMKI="
